runtime: nodejs
env: flex

vpc_access_connector:
  name: projects/appstract/locations/us-east4/connectors/appstract-connector-1
  
env_variables:
  NODE_ENV: production

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto